name: mongo-sharding-repl

services:

  configsvr:
    image: mongo:5.0
    container_name: configsvr
    command: mongod --configsvr --replSet configReplSet --port 27019
    ports:
      - 27019:27019
    volumes:
      - configdb_data:/data/db

  # Shard1 Primary
  shard1:
    image: mongo:5.0
    container_name: shard1
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018
    ports:
      - 27018:27018
    volumes:
      - shard1_data:/data/db

  # Shard1 Secondary 1
  shard1-secondary1:
    image: mongo:5.0
    container_name: shard1-secondary1
    command: mongod --shardsvr --replSet shard1ReplSet --port 27028
    ports:
      - 27028:27028
    volumes:
      - shard1_secondary1_data:/data/db

  # Shard1 Secondary 2
  shard1-secondary2:
    image: mongo:5.0
    container_name: shard1-secondary2
    command: mongod --shardsvr --replSet shard1ReplSet --port 27038
    ports:
      - 27038:27038
    volumes:
      - shard1_secondary2_data:/data/db

  # Shard2 Primary
  shard2:
    image: mongo:5.0
    container_name: shard2
    command: mongod --shardsvr --replSet shard2ReplSet --port 27020
    ports:
      - 27020:27020
    volumes:
      - shard2_data:/data/db

  # Shard2 Secondary 1
  shard2-secondary1:
    image: mongo:5.0
    container_name: shard2-secondary1
    command: mongod --shardsvr --replSet shard2ReplSet --port 27030
    ports:
      - 27030:27030
    volumes:
      - shard2_secondary1_data:/data/db

  # Shard2 Secondary 2
  shard2-secondary2:
    image: mongo:5.0
    container_name: shard2-secondary2
    command: mongod --shardsvr --replSet shard2ReplSet --port 27040
    ports:
      - 27040:27040
    volumes:
      - shard2_secondary2_data:/data/db

  mongos:
    image: mongo:5.0
    container_name: mongos
    command: mongos --configdb configReplSet/configsvr:27019 --port 27017 --bind_ip_all
    ports:
      - 27017:27017
    depends_on:
      - configsvr
      - shard1
      - shard1-secondary1
      - shard1-secondary2
      - shard2
      - shard2-secondary1
      - shard2-secondary2

  pymongo-api:
    image: kazhem/pymongo_api:1.0.0
    container_name: pymongo_api
    ports:
      - 8000:8080
    depends_on:
      - mongos
    environment:
      MONGODB_URL: mongodb://mongos:27017/somedb
      MONGODB_DATABASE_NAME: somedb

volumes:
  configdb_data:
  shard1_data:
  shard1_secondary1_data:
  shard1_secondary2_data:
  shard2_data:
  shard2_secondary1_data:
  shard2_secondary2_data:
